name: untitled2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.0
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  http: ^0.13.6
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  badges: ^2.0.3
  shared_preferences: ^2.2.1
  five_pointed_star: ^1.0.1
  toast: ^0.2.9
  like_button: ^2.0.5
  collection: ^1.17.1
  carousel_indicator: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

